using System.ComponentModel.DataAnnotations;
namespace Shop.Domain.Enum
{
    public enum SizeOfProduct
    {
        [Display(Name = "Ч - XS")]
        MXS = 0,
        [Display(Name = "Ч - S")]
        MS = 1,
        [Display(Name = "Ч - M")]
        MM = 2,
        [Display(Name = "Ч - L")]
        ML = 3,
        [Display(Name = "Ч - XL")]
        MXL = 4,
        [Display(Name = "Ч - XXL")]
        MXXL = 5,
        [Display(Name = "Ч - XXXL")]
        MXXXL = 6,
        [Display(Name = "Ж - XS")]
        WXS = 7,
        [Display(Name = "Ж - S")]
        WS = 8,
        [Display(Name = "Ж - M")]
        WM = 9,
        [Display(Name = "Ж - L")]
        WL = 10,
        [Display(Name = "Ж - XL")]
        WXL = 11,
        [Display(Name = "Ж - XXL")]
        WXXL = 12,
        [Display(Name = "Ж - XXXL")]
        WXXXL = 13,
        [Display(Name = "Ж - BXL")]
        WBXL = 14,
        [Display(Name = "Ж - BXXL")]
        WBXXL = 15,
        [Display(Name = "Ж - BXXXL")]
        WBXXXL = 16,
        [Display(Name = "Взуття - 16")]
        S16 = 17,
        [Display(Name = "Взуття - 16.5")]
        S165 = 18,
        [Display(Name = "Взуття - 17")]
        S17 = 19,
        [Display(Name = "Взуття - 18")]
        S18 = 20,
        [Display(Name = "Взуття - 19")]
        S19 = 21,
        [Display(Name = "Взуття - 19.5")]
        S195 = 22,
        [Display(Name = "Взуття - 20")]
        S20 = 23,
        [Display(Name = "Взуття - 21")]
        S21 = 24,
        [Display(Name = "Взуття - 22")]
        S22 = 25,
        [Display(Name = "Взуття - 22.5")]
        S225 = 26,
        [Display(Name = "Взуття - 23")]
        S23 = 27,
        [Display(Name = "Взуття - 24")]
        S24 = 28,
        [Display(Name = "Взуття - 25")]
        S25 = 29,
        [Display(Name = "Взуття - 26")]
        S26 = 30,
        [Display(Name = "Взуття - 27")]
        S27 = 31,
        [Display(Name = "Взуття - 28")]
        S28 = 32,
        [Display(Name = "Взуття - 28.5")]
        S285 = 33,
        [Display(Name = "Взуття - 29")]
        S29 = 34,
        [Display(Name = "Взуття - 30")]
        S30 = 35,
        [Display(Name = "Взуття - 31")]
        S31 = 36,
        [Display(Name = "Взуття - 31.5")]
        S315 = 37,
        [Display(Name = "Взуття - 32")]
        S32 = 38,
        [Display(Name = "Взуття - 33")]
        S33 = 39,
        [Display(Name = "Взуття - 34")]
        S34 = 40,
        [Display(Name = "Взуття - 34.5")]
        S345 = 41,
        [Display(Name = "Взуття - 35")]
        S35 = 42,
        [Display(Name = "Взуття - 36")]
        S36 = 43,
        [Display(Name = "Взуття - 37")]
        S37 = 44,
        [Display(Name = "Взуття - 38")]
        S38 = 45,
        [Display(Name = "Взуття - 39")]
        S39 = 46,
        [Display(Name = "Взуття - 40")]
        S40 = 47,
        [Display(Name = "Взуття - 41")]
        S41 = 48,
        [Display(Name = "Взуття - 42")]
        S42 = 49,
        [Display(Name = "Взуття - 43")]
        S43 = 50,
        [Display(Name = "Взуття - 44")]
        S44 = 51,
        [Display(Name = "Взуття - 45")]
        S45 = 52,
        [Display(Name = "Взуття - 46")]
        S46 = 53,
        [Display(Name = "Взуття - 47")]
        S47 = 54,
        [Display(Name = "Взуття - 48")]
        S48 = 55
    }
}
